//*Listar
//GET http://localhost:8080/mascotas/list HTTP/1.1
//Content-Type: application/xml

//*Buscar
//GET http://localhost:8080/mascotas/buscar?id=1 HTTP/1.1

//*Aregar
//POST http://localhost:8080/mascotas/agregar
//Content-Type: application/x-www-form-urlencoded

//nombre=Euclides
//&raza=Pastor
//&color=Marron

//*Actualizar
//PUT http://localhost:8080/mascotas/update
//Content-Type: application/x-www-form-urlencoded

//id=1
//&nombre=Euclides2
//&raza=Pastor2
//&color=Marron2

//*ELIMINAR
//DELETE http://localhost:8080/mascotas/eliminar?id=1
//Content-Type: application/x-www-form-urlencoded



